//! Test vectors: generated by this code from fixed seeds, checked for drift by a test.
//!
//! Everything deterministic (issuer keys, uniqueness keys, pseudonyms for a given credential)
//! is regenerated and compared. Everything randomised (commitments, signatures, proofs) is
//! recorded and re-verified: a recorded presentation must still verify, and every must-fail
//! case must still fail with the recorded error. The vectors prove this implementation agrees
//! with itself over time; they say nothing about interoperability with other implementations.

use crate::attributes::{Disclosed, Disclosure};
use crate::error::EnrolError;
use crate::holder::{Credential, Holder, Presentation};
use crate::identity::{IdentityProvider, MockIdProvider};
use crate::issuer::{Issuer, IssuerKey, IssuerSecret};
use crate::uniqueness::{MemoryStore, UniquenessKey};
use crate::verifier::verify;
use crate::{CREDENTIAL_HEADER, SUITE_ID};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;

/// Schema name of the vectors file.
pub const SCHEMA: &str = "d2.door.vectors/1";

const VALID_FROM: &str = "2026-01-01T00:00:00Z";
const VALID_TO: &str = "2026-12-31T23:59:59Z";

/// The seeds everything is derived from. Test material only: these are published in git and
/// must never be used for a real Door.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Seeds {
    /// Issuer key material (BBS KeyGen input), hex.
    pub issuer: String,
    /// OPRF key seed, hex.
    pub oprf: String,
    /// A second, unrelated issuer seed for the "other issuer" case, hex.
    pub other_issuer: String,
}

/// One uniqueness-key case.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UniquenessCase {
    /// The mock person id.
    pub person_id: String,
    /// `u`, hex.
    pub u: String,
}

/// The recorded refusal of a second enrolment.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SecondEnrolment {
    /// First token enrolled.
    pub first_token: String,
    /// Second token of the same person, refused.
    pub second_token: String,
    /// Epoch.
    pub epoch: u32,
    /// Error code the second enrolment gets.
    pub error: String,
}

/// A recorded credential with the seeds it came from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CredentialCase {
    /// Which demo person.
    pub holder: String,
    /// The mock token enrolled.
    pub token: String,
    /// Seed of the holder's secret `s`, hex.
    pub holder_seed: String,
    /// Revocation handle Door drew, hex.
    pub rid: String,
    /// Seed of Door's pseudonym entropy, hex.
    pub entropy_seed: String,
    /// The finalised credential.
    pub credential: Credential,
}

/// A pseudonym the recorded credential must reproduce.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PseudonymCase {
    /// Which demo person.
    pub holder: String,
    /// Context id.
    pub context: String,
    /// Compressed G1 point, hex.
    pub pseudonym: String,
    /// Short text form.
    pub nym: String,
}

/// Expected outcome of verifying a presentation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Expect {
    /// Verifies, disclosing exactly this.
    Ok {
        /// What the verifier learns.
        disclosed: Disclosed,
    },
    /// Fails with this [`VerifyError::code`].
    Err {
        /// The error code.
        error: String,
    },
}

/// A recorded presentation and how the verifier must treat it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PresentationCase {
    /// Case name.
    pub name: String,
    /// What the case shows.
    pub note: String,
    /// Which demo person made it.
    pub holder: String,
    /// The issuer key the verifier uses.
    pub issuer_key: IssuerKey,
    /// The verifier's own context.
    pub context: String,
    /// The verifier's challenge, hex.
    pub challenge: String,
    /// What the verifier requires.
    pub required: Disclosure,
    /// The presentation as received (possibly tampered).
    pub presentation: Presentation,
    /// Expected outcome.
    pub expect: Expect,
}

/// A presentation, as JSON, that must be refused when it is parsed, before `verify` runs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UnparseableCase {
    /// Case name.
    pub name: String,
    /// What the case shows.
    pub note: String,
    /// The presentation as received.
    pub presentation: serde_json::Value,
    /// The field that is malformed.
    pub field: String,
    /// Error code: always `malformed`.
    pub error: String,
}

/// The vectors file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Vectors {
    /// [`SCHEMA`].
    pub schema: String,
    /// Which code generated the file.
    pub generated_by: String,
    /// Provenance warning.
    pub warning: String,
    /// BBS ciphersuite.
    pub ciphersuite: String,
    /// Which drafts the BBS library implements.
    pub drafts: Vec<String>,
    /// Credential header, as text.
    pub credential_header: String,
    /// Seeds.
    pub seeds: Seeds,
    /// Issuer keys for epochs 1 and 2, derived from `seeds.issuer`.
    pub issuer_keys: Vec<IssuerKey>,
    /// Uniqueness keys for the demo people, derived from `seeds.oprf`.
    pub uniqueness: Vec<UniquenessCase>,
    /// The refused second enrolment.
    pub second_enrolment: SecondEnrolment,
    /// Recorded credentials.
    pub credentials: Vec<CredentialCase>,
    /// Pseudonyms the recorded credentials must reproduce.
    pub pseudonyms: Vec<PseudonymCase>,
    /// Recorded presentations, passing and failing.
    pub presentations: Vec<PresentationCase>,
    /// Presentations that must not even parse.
    pub unparseable: Vec<UnparseableCase>,
}

fn seed(label: &str) -> [u8; 32] {
    // Fixed, public, obviously-test-only derivation of each seed from its label.
    Sha256::digest(format!("d2.door test seed: {label}").as_bytes()).into()
}

fn h(bytes: &[u8]) -> String {
    hex::encode(bytes)
}

const PEOPLE: [(&str, &str); 3] = [
    ("alice", "alice-phone"),
    ("bob", "bob-phone"),
    ("carol", "carol-phone"),
];

/// Generate the vectors. Deterministic parts come out the same every run; recorded parts are
/// fresh and verified before they are returned.
pub fn generate() -> Result<Vectors, String> {
    let seeds = Seeds {
        issuer: h(&seed("issuer")),
        oprf: h(&seed("oprf")),
        other_issuer: h(&seed("other issuer")),
    };
    let provider = MockIdProvider::demo();
    let mut issuer = Issuer::new(UniquenessKey::from_seed(seed("oprf")), MemoryStore::new());
    for epoch in [1u32, 2] {
        issuer
            .add_epoch(IssuerSecret::from_seed(
                epoch,
                VALID_FROM,
                VALID_TO,
                &seed("issuer"),
            ))
            .map_err(|e| e.to_string())?;
    }
    let issuer_keys = issuer.issuer_keys();
    let key1 = issuer_keys[0].clone();
    let key2 = issuer_keys[1].clone();
    let other_key = IssuerSecret::from_seed(1, VALID_FROM, VALID_TO, &seed("other issuer"))
        .public()
        .clone();

    let mut uniqueness = Vec::new();
    for id in ["test-person-0001", "test-person-0002", "test-person-0003"] {
        uniqueness.push(UniquenessCase {
            person_id: id.to_string(),
            u: issuer.uniqueness_key(id),
        });
    }

    // Enrol the three demo people in epoch 1.
    let mut credentials = Vec::new();
    let mut by_holder: BTreeMap<String, Credential> = BTreeMap::new();
    for (holder, token) in PEOPLE {
        let assertion = provider.assert_identity(token).map_err(|e| e.to_string())?;
        let holder_seed = seed(&format!("holder {holder}"));
        let rid = seed(&format!("rid {holder}"));
        let entropy_seed = seed(&format!("entropy {holder}"));
        let h = Holder::from_seed(&holder_seed);
        let commit = h.commit().map_err(|e| e.to_string())?;
        let issuance = issuer
            .enrol_with(&assertion, 1, &commit.commitment, rid, &entropy_seed)
            .map_err(|e| e.to_string())?;
        let credential = h
            .finalize(&key1, &issuance, &commit.blind)
            .map_err(|e| e.to_string())?;
        by_holder.insert(holder.to_string(), credential.clone());
        credentials.push(CredentialCase {
            holder: holder.to_string(),
            token: token.to_string(),
            holder_seed: hex::encode(holder_seed),
            rid: hex::encode(rid),
            entropy_seed: hex::encode(entropy_seed),
            credential,
        });
    }

    // Alice's second device is refused.
    let second = {
        let assertion = provider
            .assert_identity("alice-tablet")
            .map_err(|e| e.to_string())?;
        let h = Holder::from_seed(&seed("holder alice tablet"));
        let commit = h.commit().map_err(|e| e.to_string())?;
        match issuer.enrol_with(&assertion, 1, &commit.commitment, seed("rid 2"), b"e") {
            Err(EnrolError::AlreadyEnrolled { epoch }) => SecondEnrolment {
                first_token: "alice-phone".into(),
                second_token: "alice-tablet".into(),
                epoch,
                error: "already_enrolled".into(),
            },
            other => return Err(format!("second enrolment was not refused: {other:?}")),
        }
    };

    let alice = &by_holder["alice"];
    let bob = &by_holder["bob"];
    let carol = &by_holder["carol"];
    let esch = Disclosure {
        jurisdiction_levels: 2,
        adult: true,
        epoch: true,
    };
    let country = Disclosure {
        jurisdiction_levels: 1,
        adult: false,
        epoch: false,
    };
    let adult_only = Disclosure {
        jurisdiction_levels: 0,
        adult: true,
        epoch: false,
    };
    let nothing = Disclosure::default();

    let mut pseudonyms = Vec::new();
    for (holder, cred) in [("alice", alice), ("bob", bob), ("carol", carol)] {
        for context in ["agora:lu.esch", "agora:lu", "booth:round-1"] {
            let p = cred
                .present(&key1, context, b"", &nothing)
                .map_err(|e| e.to_string())?;
            pseudonyms.push(PseudonymCase {
                holder: holder.into(),
                context: context.into(),
                pseudonym: p.pseudonym.as_hex(),
                nym: p.pseudonym.nym(),
            });
        }
    }

    let present = |cred: &Credential, context: &str, challenge: &[u8], d: &Disclosure| {
        cred.present(&key1, context, challenge, d)
            .map_err(|e| e.to_string())
    };
    let ok = |p: &Presentation| Expect::Ok {
        disclosed: p.disclosed.clone(),
    };
    let err = |code: &str| Expect::Err { error: code.into() };
    let case = |name: &str,
                note: &str,
                holder: &str,
                key: &IssuerKey,
                context: &str,
                challenge: &[u8],
                required: Disclosure,
                presentation: Presentation,
                expect: Expect| PresentationCase {
        name: name.into(),
        note: note.into(),
        holder: holder.into(),
        issuer_key: key.clone(),
        context: context.into(),
        challenge: hex::encode(challenge),
        required,
        presentation,
        expect,
    };

    let mut cases = Vec::new();

    let a1 = present(alice, "agora:lu.esch", b"challenge-1", &esch)?;
    cases.push(case(
        "alice_esch",
        "Adult in Esch proves lives-in-lu.esch, adult and epoch 1 to the Esch Agora.",
        "alice",
        &key1,
        "agora:lu.esch",
        b"challenge-1",
        esch,
        a1.clone(),
        ok(&a1),
    ));
    let a2 = present(alice, "agora:lu.esch", b"challenge-2", &esch)?;
    cases.push(case(
        "alice_esch_again",
        "Same holder, same context, new challenge: a different proof but the same pseudonym.",
        "alice",
        &key1,
        "agora:lu.esch",
        b"challenge-2",
        esch,
        a2.clone(),
        ok(&a2),
    ));
    let a3 = present(alice, "agora:lu", b"challenge-3", &country)?;
    cases.push(case(
        "alice_country",
        "Same holder in the national Agora: only the country is disclosed and the pseudonym differs.",
        "alice", &key1, "agora:lu", b"challenge-3", country, a3.clone(), ok(&a3),
    ));
    let b1 = present(bob, "commons:matter-12", b"challenge-4", &nothing)?;
    cases.push(case(
        "bob_nothing_disclosed",
        "A valid credential with no attribute disclosed: only the pseudonym is learnt.",
        "bob",
        &key1,
        "commons:matter-12",
        b"challenge-4",
        nothing,
        b1.clone(),
        ok(&b1),
    ));
    let c1 = present(carol, "booth:round-1", b"challenge-5", &adult_only)?;
    cases.push(case(
        "carol_minor_honest",
        "A minor's honest presentation discloses adult=false; the verifier sees it.",
        "carol",
        &key1,
        "booth:round-1",
        b"challenge-5",
        adult_only,
        c1.clone(),
        ok(&c1),
    ));

    // Must-fail cases.
    cases.push(case(
        "wrong_epoch_key",
        "An epoch-1 presentation checked against the epoch-2 key.",
        "alice",
        &key2,
        "agora:lu.esch",
        b"challenge-1",
        esch,
        a1.clone(),
        err("epoch_mismatch"),
    ));
    let mut t = a1.clone();
    t.epoch = 2;
    t.disclosed.epoch = Some(2);
    cases.push(case(
        "forged_epoch",
        "The epoch fields edited to 2 and checked against the epoch-2 key: the proof is bound to the key.",
        "alice", &key2, "agora:lu.esch", b"challenge-1", esch, t, err("invalid_proof"),
    ));
    cases.push(case(
        "other_issuer",
        "A key for epoch 1 from a different Door.",
        "alice",
        &other_key,
        "agora:lu.esch",
        b"challenge-1",
        esch,
        a1.clone(),
        err("invalid_proof"),
    ));
    let mut t = c1.clone();
    t.disclosed.adult = Some(true);
    cases.push(case(
        "tampered_adult",
        "The minor's presentation with adult edited to true.",
        "carol",
        &key1,
        "booth:round-1",
        b"challenge-5",
        adult_only,
        t,
        err("invalid_proof"),
    ));
    let mut t = a1.clone();
    t.disclosed.jurisdiction_path = Some("lu.luxembourg".into());
    cases.push(case(
        "tampered_jurisdiction",
        "Disclosed jurisdiction edited to another commune.",
        "alice",
        &key1,
        "agora:lu.esch",
        b"challenge-1",
        esch,
        t,
        err("invalid_proof"),
    ));
    cases.push(case(
        "replayed_context",
        "A presentation for agora:lu.esch replayed to the agora:lu verifier.",
        "alice",
        &key1,
        "agora:lu",
        b"challenge-1",
        esch,
        a1.clone(),
        err("context_mismatch"),
    ));
    let mut t = a1.clone();
    t.context = "agora:lu".into();
    cases.push(case(
        "replayed_context_forged",
        "The same replay with the context field edited: the pseudonym proof is bound to the context.",
        "alice", &key1, "agora:lu", b"challenge-1", esch, t, err("invalid_proof"),
    ));
    cases.push(case(
        "replayed_challenge",
        "A presentation replayed against a new challenge.",
        "alice",
        &key1,
        "agora:lu.esch",
        b"challenge-9",
        esch,
        a1.clone(),
        err("challenge_mismatch"),
    ));
    let mut t = a1.clone();
    t.challenge = hex::encode(b"challenge-9");
    cases.push(case(
        "replayed_challenge_forged",
        "The same replay with the challenge field edited: the proof is bound to the challenge.",
        "alice",
        &key1,
        "agora:lu.esch",
        b"challenge-9",
        esch,
        t,
        err("invalid_proof"),
    ));
    let hidden = present(carol, "booth:round-1", b"challenge-6", &nothing)?;
    cases.push(case(
        "missing_disclosure",
        "The verifier requires adult; the presentation hides it.",
        "carol",
        &key1,
        "booth:round-1",
        b"challenge-6",
        adult_only,
        hidden,
        err("missing_disclosure"),
    ));
    let mut t = b1.clone();
    t.pseudonym = a1.pseudonym.clone();
    cases.push(case(
        "swapped_pseudonym",
        "Bob's proof with Alice's pseudonym.",
        "bob",
        &key1,
        "commons:matter-12",
        b"challenge-4",
        nothing,
        t,
        err("invalid_proof"),
    ));
    let mut t = a1.clone();
    t.proof.truncate(t.proof.len() - 64);
    cases.push(case(
        "truncated_proof",
        "A proof shorter than its disclosure implies: rejected before decoding.",
        "alice",
        &key1,
        "agora:lu.esch",
        b"challenge-1",
        esch,
        t,
        err("malformed"),
    ));
    let mut t = a1.clone();
    let mut bytes = hex::decode(&t.proof).map_err(|e| e.to_string())?;
    let last = bytes.len() - 1;
    bytes[last] ^= 1;
    t.proof = hex::encode(bytes);
    cases.push(case(
        "flipped_proof_bit",
        "Lowest bit of the proof's challenge scalar flipped.",
        "alice",
        &key1,
        "agora:lu.esch",
        b"challenge-1",
        esch,
        t,
        err("invalid_proof"),
    ));

    // Must-not-parse cases: a valid presentation with only the pseudonym field broken.
    let mut unparseable = Vec::new();
    let a1_json = serde_json::to_value(&a1).map_err(|e| e.to_string())?;
    let a1_nym = a1.pseudonym.as_hex();
    for (name, note, value) in [
        (
            "pseudonym_short",
            "A one-byte pseudonym: refused at parsing, never reaches the BBS library.",
            "ab".to_string(),
        ),
        (
            "pseudonym_not_hex",
            "A pseudonym that is not hex.",
            "zz".to_string(),
        ),
        (
            "pseudonym_uppercase",
            "The right pseudonym in uppercase hex: one point has one spelling only.",
            a1_nym.to_uppercase(),
        ),
        (
            "pseudonym_47_bytes",
            "A pseudonym one byte short of a compressed G1 point.",
            a1_nym[..94].to_string(),
        ),
    ] {
        let mut presentation = a1_json.clone();
        presentation["pseudonym"] = serde_json::Value::String(value);
        unparseable.push(UnparseableCase {
            name: name.into(),
            note: note.into(),
            presentation,
            field: "pseudonym".into(),
            error: "malformed".into(),
        });
    }

    let vectors = Vectors {
        schema: SCHEMA.into(),
        generated_by: format!(
            "d2-door {} (modules/door): `cargo run -p d2-door -- vectors --out spec/door/vectors.json`",
            env!("CARGO_PKG_VERSION")
        ),
        warning: "Generated by this implementation from the public test seeds below. These are \
                  not vectors from another implementation or from the IRTF drafts: they prove \
                  that this code agrees with itself over time, not that it interoperates. The \
                  seeds are published and must never be used for a real Door."
            .into(),
        ciphersuite: SUITE_ID.into(),
        drafts: vec![
            "draft-irtf-cfrg-bbs-signatures-12".into(),
            "draft-irtf-cfrg-bbs-blind-signatures-02".into(),
            "draft-irtf-cfrg-bbs-per-verifier-linkability-03".into(),
            "RFC 9497 OPRF, ristretto255-SHA512".into(),
        ],
        credential_header: String::from_utf8_lossy(CREDENTIAL_HEADER).into_owned(),
        seeds,
        issuer_keys,
        uniqueness,
        second_enrolment: second,
        credentials,
        pseudonyms,
        presentations: cases,
        unparseable,
    };
    check(&vectors)?;
    Ok(vectors)
}

/// Check a vectors file against the code: regenerate what is deterministic, re-verify what
/// is recorded. Returns the number of checks made.
pub fn check(v: &Vectors) -> Result<usize, String> {
    let mut checks = 0;
    if v.schema != SCHEMA {
        return Err(format!("schema {:?}, expected {SCHEMA:?}", v.schema));
    }
    let issuer_seed = decode32(&v.seeds.issuer, "seeds.issuer")?;
    let oprf_seed = decode32(&v.seeds.oprf, "seeds.oprf")?;

    // Issuer keys regenerate.
    for key in &v.issuer_keys {
        let again =
            IssuerSecret::from_seed(key.epoch, &key.valid_from, &key.valid_to, &issuer_seed);
        if again.public() != key {
            return Err(format!("issuer key for epoch {} drifted", key.epoch));
        }
        checks += 1;
    }

    // Uniqueness keys regenerate.
    let oprf = UniquenessKey::from_seed(oprf_seed);
    for case in &v.uniqueness {
        if oprf.uniqueness_key(&case.person_id) != case.u {
            return Err(format!("u for {} drifted", case.person_id));
        }
        checks += 1;
    }

    // The second enrolment is still refused (fresh run with the same seeds).
    {
        let provider = MockIdProvider::demo();
        let mut issuer = Issuer::new(UniquenessKey::from_seed(oprf_seed), MemoryStore::new());
        let e = v.second_enrolment.epoch;
        issuer
            .add_epoch(IssuerSecret::from_seed(
                e,
                VALID_FROM,
                VALID_TO,
                &issuer_seed,
            ))
            .map_err(|e| e.to_string())?;
        for (i, token) in [
            &v.second_enrolment.first_token,
            &v.second_enrolment.second_token,
        ]
        .into_iter()
        .enumerate()
        {
            let assertion = provider.assert_identity(token).map_err(|e| e.to_string())?;
            let commit = Holder::from_seed(token.as_bytes())
                .commit()
                .map_err(|e| e.to_string())?;
            let result = issuer.enrol_with(&assertion, e, &commit.commitment, [i as u8; 32], b"x");
            match (i, result) {
                (0, Ok(_)) => {}
                (1, Err(EnrolError::AlreadyEnrolled { .. }))
                    if v.second_enrolment.error == "already_enrolled" => {}
                (_, other) => return Err(format!("second enrolment case: unexpected {other:?}")),
            }
        }
        checks += 1;
    }

    // Recorded credentials still present and verify; pseudonyms reproduce.
    let creds: BTreeMap<&str, &Credential> = v
        .credentials
        .iter()
        .map(|c| (c.holder.as_str(), &c.credential))
        .collect();
    let key_for = |epoch: u32| {
        v.issuer_keys
            .iter()
            .find(|k| k.epoch == epoch)
            .ok_or_else(|| format!("no issuer key for epoch {epoch}"))
    };
    for case in &v.pseudonyms {
        let cred = creds
            .get(case.holder.as_str())
            .ok_or_else(|| format!("no credential for {}", case.holder))?;
        let key = key_for(cred.epoch)?;
        let p = cred
            .present(key, &case.context, b"", &Disclosure::default())
            .map_err(|e| format!("{} in {}: {e}", case.holder, case.context))?;
        if p.pseudonym.as_hex() != case.pseudonym || p.pseudonym.nym() != case.nym {
            return Err(format!(
                "pseudonym of {} in {} drifted",
                case.holder, case.context
            ));
        }
        verify(key, &p, &case.context, b"", &Disclosure::default())
            .map_err(|e| format!("fresh presentation of {}: {e}", case.holder))?;
        checks += 1;
    }

    // Recorded presentations behave as recorded.
    for case in &v.presentations {
        let challenge = hex::decode(&case.challenge).map_err(|e| format!("{}: {e}", case.name))?;
        let result = verify(
            &case.issuer_key,
            &case.presentation,
            &case.context,
            &challenge,
            &case.required,
        );
        match (&case.expect, result) {
            (Expect::Ok { disclosed }, Ok(verified)) => {
                if &verified.disclosed != disclosed {
                    return Err(format!(
                        "{}: disclosed {:?}, expected {:?}",
                        case.name, verified.disclosed, disclosed
                    ));
                }
                if verified.pseudonym != case.presentation.pseudonym {
                    return Err(format!("{}: pseudonym changed in verification", case.name));
                }
            }
            (Expect::Err { error }, Err(e)) => {
                if e.code() != error {
                    return Err(format!(
                        "{}: failed with {:?}, expected {error:?}",
                        case.name,
                        e.code()
                    ));
                }
            }
            (expect, result) => {
                return Err(format!(
                    "{}: got {result:?}, expected {expect:?}",
                    case.name
                ));
            }
        }
        checks += 1;
    }

    // Unparseable presentations are refused when parsed, naming the broken field.
    for case in &v.unparseable {
        match serde_json::from_value::<Presentation>(case.presentation.clone()) {
            Ok(_) => return Err(format!("{}: parsed, expected {}", case.name, case.error)),
            Err(e) if case.error == "malformed" && e.to_string().contains(&case.field) => {}
            Err(e) => return Err(format!("{}: refused for another reason: {e}", case.name)),
        }
        checks += 1;
    }

    // Cross-case facts the vectors exist to show.
    let find = |name: &str| {
        v.presentations
            .iter()
            .find(|c| c.name == name)
            .ok_or_else(|| format!("missing case {name}"))
    };
    let (a1, a2, a3) = (
        find("alice_esch")?,
        find("alice_esch_again")?,
        find("alice_country")?,
    );
    if a1.presentation.pseudonym != a2.presentation.pseudonym {
        return Err("same context gave different pseudonyms".into());
    }
    if a1.presentation.proof == a2.presentation.proof {
        return Err("two presentations reused a proof".into());
    }
    if a1.presentation.pseudonym == a3.presentation.pseudonym {
        return Err("different contexts gave the same pseudonym".into());
    }
    checks += 3;
    Ok(checks)
}

fn decode32(hex_str: &str, what: &str) -> Result<[u8; 32], String> {
    hex::decode(hex_str)
        .ok()
        .and_then(|b| b.try_into().ok())
        .ok_or_else(|| format!("{what}: expected 32 bytes of hex"))
}
