"""Generate spec/lottery/vectors/draws.json from the recorded beacons in beacons.json.

    uv run python -m d2_lottery.vectors --out spec/lottery/vectors/draws.json

Pools are synthetic. Beacons are real recorded ones (see beacons.json for where each came from).
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
from pathlib import Path
from typing import Any

from .drand import KNOWN_CHAINS, Beacon, ChainInfo, verify_beacon
from .draw import Commitment, Stream, panel, run_draw, seed
from .pool import Pool
from .transcript import build

ROOT = Path(__file__).resolve().parents[4]
BEACONS = ROOT / "spec" / "lottery" / "vectors" / "beacons.json"
AGES = ("18-34", "35-54", "55-plus")


def recorded() -> dict[str, dict[str, Any]]:
    return {b["name"]: b for b in json.loads(BEACONS.read_text("utf-8"))["beacons"]}


def synthetic_pool(n: int, label: str, stratified: bool) -> Pool:
    members = []
    for i in range(n):
        nym = "nym-" + hashlib.sha256(f"{label}/{i}".encode()).hexdigest()[:20]
        strata = {"age": AGES[i % 3], "commune": "esch" if i % 2 else "dudelange"}
        members.append({"nym": nym, "strata": strata if stratified else {}})
    return Pool(members)


def _commitment(pool: Pool, chain: ChainInfo, round_: int, **kw: Any) -> Commitment:
    return Commitment(
        committed_at=chain.round_time(round_) - 7200,
        pool_root=pool.root_hex,
        pool_size=len(pool),
        chain=chain.hash,
        scheme=chain.scheme,
        round=round_,
        **kw,
    )


def _stream_vector(seed_hex: str, ranges: list[int]) -> dict[str, Any]:
    s = Stream(bytes.fromhex(seed_hex))
    words = [str(s.u64()) for _ in range(6)]
    s = Stream(bytes.fromhex(seed_hex))
    return {
        "seed": seed_hex,
        "u64": words,
        "below": [{"n": str(n), "value": str(s.below(n))} for n in ranges],
    }


def build_vectors() -> dict[str, Any]:
    rec = recorded()
    default = KNOWN_CHAINS["default"]
    walk = rec["walkthrough-rfc9380-38"]
    walk_chain = ChainInfo.from_dict(walk["chain_info"])
    b_default = Beacon.from_dict(rec["default-mainnet-2634945"]["beacon"])
    b_walk = Beacon.from_dict(walk["beacon"])

    small = synthetic_pool(5, "small", stratified=True)
    plain = synthetic_pool(20, "plain", stratified=False)
    strat = synthetic_pool(30, "strat", stratified=True)

    c_plain = _commitment(
        plain, default, b_default.round, purpose="review-panel", context="matter-0001", size=5
    )
    c_strat = _commitment(
        strat,
        walk_chain,
        b_walk.round,
        purpose="briefing-panel",
        context="matter-0002",
        size=6,
        stratify_by="age",
        quotas={"18-34": 2, "35-54": 2, "55-plus": 2},
    )
    c_one = _commitment(
        small, default, b_default.round, purpose="scope-challenge", context="matter-0003", size=1
    )

    draws = [
        {
            "name": "plain-default-mainnet",
            "trusted_chain_info": None,
            "transcript": build(c_plain, plain, default, b_default),
        },
        {
            "name": "stratified-walkthrough",
            "trusted_chain_info": walk_chain.to_dict(),
            "transcript": build(c_strat, strat, walk_chain, b_walk),
        },
        {
            "name": "single-seat",
            "trusted_chain_info": None,
            "transcript": build(c_one, small, default, b_default),
        },
    ]
    for d in draws:
        d["commitment_text"] = Commitment.from_dict(d["transcript"]["commitment"]).text()
        randomness = bytes.fromhex(d["transcript"]["beacon"]["randomness"])
        d["seed"] = seed(Commitment.from_dict(d["transcript"]["commitment"]), randomness).hex()

    pool_vectors = {
        "members": small.to_list(),
        "leaf_data": [m.leaf_data().decode("ascii") for m in small.members],
        "root": small.root_hex,
        "inclusion": [small.inclusion_proof(m.nym) for m in small.members],
    }

    replacements: dict[str, Any] = {
        "draw": "stratified-walkthrough",
        "declined": [
            draws[1]["transcript"]["result"]["selected"][0],
            draws[1]["transcript"]["result"]["groups"][0]["order"][2],
        ],
    }
    replacements["panel"] = panel(draws[1]["transcript"]["result"], replacements["declined"])

    return {
        "about": "Lottery draw vectors (spec/lottery/README.md). Pools are synthetic; beacons are "
        "the recorded real ones in beacons.json. Generated by d2_lottery.vectors.",
        "pool": pool_vectors,
        "streams": [
            _stream_vector("00" * 32, [1, 2, 3, 10, 1000, 2**63 + 1]),
            _stream_vector(draws[0]["seed"], [20, 19, 18, 17, 16]),
        ],
        "draws": draws,
        "replacements": replacements,
        "invalid": invalid_cases(draws),
    }


def invalid_cases(draws: list[dict[str, Any]]) -> list[dict[str, Any]]:
    base = draws[0]["transcript"]
    walk = draws[1]
    cases: list[dict[str, Any]] = []

    def case(reason: str, mutate, src=base, trusted=None) -> None:
        t = copy.deepcopy(src)
        mutate(t)
        cases.append({"reason": reason, "trusted_chain_info": trusted, "transcript": t})

    def flip_hex(s: str, i: int = 10) -> str:
        return s[:i] + ("0" if s[i] != "0" else "1") + s[i + 1 :]

    case("pool member added", lambda t: t["pool"].append({"nym": "nym-intruder", "strata": {}}))
    case("pool member removed", lambda t: t["pool"].pop())
    case("pool member renamed", lambda t: t["pool"][0].update(nym="nym-renamed"))
    case("selected list edited", lambda t: t["result"]["selected"].reverse())
    case("order edited", lambda t: t["result"]["groups"][0]["order"].reverse())
    case("commitment purpose changed", lambda t: t["commitment"].update(purpose="other"))
    case("commitment size changed", lambda t: t["commitment"].update(size=6))
    case(
        "beacon round differs from commitment",
        lambda t: t["beacon"].update(round=t["beacon"]["round"] + 1),
    )
    case(
        "signature tampered",
        lambda t: t["beacon"].update(signature=flip_hex(t["beacon"]["signature"])),
    )
    case(
        "randomness not sha256 of signature",
        lambda t: t["beacon"].update(randomness=flip_hex(t["beacon"]["randomness"])),
    )
    case(
        "previous signature tampered",
        lambda t: t["beacon"].update(
            previous_signature=flip_hex(t["beacon"]["previous_signature"])
        ),
    )
    case(
        "committed less than an hour before the round",
        lambda t: t["commitment"].update(committed_at=t["commitment"]["committed_at"] + 3601),
    )
    case("walkthrough chain not trusted by default", lambda t: None, src=walk["transcript"])
    case(
        "quota tampered",
        lambda t: t["commitment"]["quotas"].update({"18-34": 3, "35-54": 1}),
        src=walk["transcript"],
        trusted=walk["trusted_chain_info"],
    )
    case(
        "stratum value edited in pool",
        lambda t: t["pool"][0]["strata"].update(age="35-54"),
        src=walk["transcript"],
        trusted=walk["trusted_chain_info"],
    )

    # Non-canonical input (spec section 7, "Strict input"): each would hash the same bytes,
    # so both verifiers must reject it rather than disagree.
    def spaced(field: str, sep: str) -> Any:
        return lambda t: t["beacon"].update(
            {field: t["beacon"][field][:10] + sep + t["beacon"][field][10:]}
        )

    case("signature hex with a space", spaced("signature", " "))
    case("randomness hex with a newline", spaced("randomness", "\n"))
    case(
        "signature hex in uppercase",
        lambda t: t["beacon"].update(signature=t["beacon"]["signature"].upper()),
    )
    case("member strata null", lambda t: [m.update(strata=None) for m in t["pool"]])
    case("commitment quotas null", lambda t: t["commitment"].update(quotas=None))
    case("commitment version null", lambda t: t["commitment"].update(version=None))

    def drand_form(t: dict[str, Any]) -> None:
        ci = t["chain_info"]
        t["chain_info"] = {
            "public_key": ci["public_key"],
            "period": ci["period"],
            "genesis_time": ci["genesis_time"],
            "groupHash": ci["group_hash"],
            "schemeID": ci["scheme"],
            "metadata": {"beaconID": ci["beacon_id"]},
        }

    case("chain_info in drand /info form", drand_form)
    case(
        "chain_info with an extra field",
        lambda t: t["chain_info"].update(hash=t["commitment"]["chain"]),
    )
    case("chain_info missing a field", lambda t: t["chain_info"].pop("beacon_id"))
    case("chain_info period as a string", lambda t: t["chain_info"].update(period="30"))
    case(
        "previous_signature null on an unchained beacon",
        lambda t: t["beacon"].update(previous_signature=None),
        src=walk["transcript"],
        trusted=walk["trusted_chain_info"],
    )

    # Number syntax only shows in the JSON text, so these cases carry the text itself.
    def text_case(reason: str, old: str, new: str) -> None:
        text = json.dumps(base)
        assert text.count(old) == 1, old
        cases.append(
            {
                "reason": reason,
                "trusted_chain_info": None,
                "transcript_json": text.replace(old, new),
            }
        )

    c = base["commitment"]
    scheme = f'"scheme": "{c["scheme"]}", '
    text_case(
        "round written as a float",
        f'{scheme}"round": {c["round"]},',
        f'{scheme}"round": {c["round"]}.0,',
    )
    assert c["pool_size"] == 20
    text_case("pool_size written with an exponent", '"pool_size": 20,', '"pool_size": 2e1,')
    return cases


def render() -> str:
    vectors = build_vectors()
    # Self-check: every beacon used verifies.
    for d in vectors["draws"]:
        info = d["trusted_chain_info"]
        chain = ChainInfo.from_dict(info) if info else KNOWN_CHAINS["default"]
        verify_beacon(chain, Beacon.from_dict(d["transcript"]["beacon"]))
        c = Commitment.from_dict(d["transcript"]["commitment"])
        pool = Pool(d["transcript"]["pool"])
        assert (
            run_draw(c, pool, bytes.fromhex(d["transcript"]["beacon"]["randomness"]))
            == (d["transcript"]["result"])
        )
    return json.dumps(vectors, indent=2) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    args.out.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
